# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Brendan Ritchie
tagline:          ''
description:      'Software developer, sometime philosopher.'
url:              https://bhritchie.github.pages
baseurl:          /

author:
  name:           'Brendan Ritchie'
  url:            https://bhritchie.github.io

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/bhritchie/bhritchie.github.io
